export interface CartaPredefinida {
  texto: string;
  tipo: 'reto' | 'pregunta' | 'hot';
}

export const cartasExtraidas: CartaPredefinida[] = [
  // ---- PREGUNTAS Y CONFESIONES ----
  { texto: "Cuenta tu sueño erótico más recurrente.", tipo: "pregunta" },
  { texto: "Cuenta tu fantasía sexual más oscura.", tipo: "pregunta" },
  { texto: "Cuenta cómo fue tu primera vez.", tipo: "pregunta" },
  { texto: "Cuenta lo más inconfesable de tu relación de pareja.", tipo: "pregunta" },
  { texto: "Confiesa en detalle con cuántas personas te has acostado.", tipo: "pregunta" },
  { texto: "Explica con lujo de detalles tu mejor polvo.", tipo: "pregunta" },
  { texto: "Cuenta el sitio más extraño en el que lo has hecho.", tipo: "pregunta" },
  { texto: "Cuenta tu lugar preferido para hacer el amor.", tipo: "pregunta" },
  { texto: "¿Has sido infiel alguna vez? Cuenta los detalles.", tipo: "pregunta" },
  { texto: "¿Has hecho el amor con más de una persona a la vez?", tipo: "pregunta" },
  { texto: "Cuenta en detalle cómo te masturbas (mientras tu pareja te quita una prenda).", tipo: "pregunta" },
  { texto: "Relata el cuento de 'Caperucita Erótica' a tu manera.", tipo: "pregunta" },
  { texto: "Sé sincer@ y dinos: ¿ya estás caliente?", tipo: "pregunta" },

  // ---- RETOS SUAVES Y JUEGOS PREVIOS ----
  { texto: "Dile que te enseñe (en privado) la parte de su cuerpo que tú quieras.", tipo: "reto" },
  { texto: "Métele mano bajo la ropa sutilmente, sin quitarle ninguna prenda.", tipo: "reto" },
  { texto: "Besa donde tu pareja te pida.", tipo: "reto" },
  { texto: "Acaricia y besa sus pechos.", tipo: "reto" },
  { texto: "Besa sus orejas y su cuello lentamente.", tipo: "reto" },
  { texto: "Bésale el ombligo eróticamente por 30 segundos.", tipo: "reto" },
  { texto: "La lengua de tu pareja hará letras en tu espalda, adivínalas.", tipo: "reto" },
  { texto: "Besa todo su cuerpo lentamente.", tipo: "reto" },
  { texto: "Haz un combate de lenguas con tu pareja por 2 minutos.", tipo: "reto" },
  { texto: "Quítate una prenda de forma sensual.", tipo: "reto" },
  { texto: "Quítale una prenda usando solo la boca.", tipo: "reto" },
  { texto: "Besaros y acariciaros muy dulcemente por un minuto.", tipo: "reto" },
  { texto: "Haz un striptease hasta quedarte en ropa interior.", tipo: "reto" },
  { texto: "Bésale locamente durante 2 minutos.", tipo: "reto" },
  { texto: "Lame y sopla suavemente por todo su cuerpo.", tipo: "reto" },
  { texto: "Chúpale los dedos de las manos uno por uno.", tipo: "reto" },
  { texto: "Tócale por encima de la ropa la parte de su cuerpo que él/ella elija.", tipo: "reto" },
  { texto: "Mordisquéale el lóbulo de la oreja suavemente.", tipo: "reto" },
  { texto: "Muestra la parte más íntima de tu cuerpo durante 5 segundos.", tipo: "reto" },
  { texto: "Dale besitos por el interior de los muslos.", tipo: "reto" },
  { texto: "Esconde una moneda en tu cuerpo y haz que tu pareja la busque sin usar las manos.", tipo: "reto" },
  { texto: "Imita cómo te masturbas frente a tu pareja.", tipo: "reto" },
  { texto: "Marca tu silueta contorneándote frente a tu pareja.", tipo: "reto" },
  { texto: "Posa vestid@ para una sesión de 5 fotos eróticas.", tipo: "reto" },
  { texto: "Pasa un cubito de hielo por su escote y recógelo con la boca.", tipo: "reto" },
  { texto: "Dar una vuelta a la habitación sujetando un folio (papel) con vuestros pechos sin que se caiga.", tipo: "reto" },
  { texto: "Acariciaos mutuamente la entrepierna con los pies.", tipo: "reto" },
  { texto: "Mide en palmos el contorno de sus caderas.", tipo: "reto" },
  { texto: "Te quitas dos prendas mientras cantas una canción a viva voz sobre una silla.", tipo: "reto" },
  { texto: "Compartan una barra de chocolate de boca en boca hasta disolverla.", tipo: "reto" },
  { texto: "Muestra tus nalgas de la manera más sensual posible.", tipo: "reto" },

  // ---- RETOS HOT Y ACCIÓN DIRECTA ----
  { texto: "Tápale los ojos y hazle lo que quieras durante 2 minutos.", tipo: "hot" },
  { texto: "Haz el amor cambiando por 5 posturas (durante no más de 5 minutos).", tipo: "hot" },
  { texto: "Átal@ a la cama y hazle lo que quieras por 5 minutos.", tipo: "hot" },
  { texto: "Mastúrbale lentamente observando su reacción.", tipo: "hot" },
  { texto: "Hagan el amor ferozmente durante 3 minutos seguidos.", tipo: "hot" },
  { texto: "Lame sus partes íntimas con devoción.", tipo: "hot" },
  { texto: "Hacer la posición del 69 durante 2 minutos.", tipo: "hot" },
  { texto: "Mastúrbate lentamente frente a tu pareja.", tipo: "hot" },
  { texto: "Hazle un masaje con todo tu cuerpo desnudo untado en aceite.", tipo: "hot" },
  { texto: "Tu pareja debe realizarte un masaje tailandés terminando con final feliz.", tipo: "hot" },
  { texto: "Hazlo boca abajo durante 2 minutos.", tipo: "hot" },
  { texto: "Practícale sexo oral de forma exquisita por 3 minutos.", tipo: "hot" },
  { texto: "Finge tu mejor orgasmo tirad@ en el piso durante 1 minuto.", tipo: "hot" },
  { texto: "Desnúdale por completo a la fuerza.", tipo: "hot" },
  { texto: "Bésale muy cerca de sus partes íntimas sin llegar a tocarlas.", tipo: "hot" },
  { texto: "Hazle un masaje con tu lengua por todo el cuerpo.", tipo: "hot" },
  { texto: "Roza tus partes íntimas con las suyas sin penetración.", tipo: "hot" },
  { texto: "Azótale las nalgas suavemente 5 veces.", tipo: "hot" },
  { texto: "Acaricia su cuerpo usando solo tus partes íntimas.", tipo: "hot" },
  { texto: "Tu pareja te realizará un masaje con sus manos durante 30 minutos terminando en lo que tú quieras.", tipo: "hot" },
  { texto: "Grábense en vídeo realizando sexo (desde los preliminares hasta el orgasmo).", tipo: "hot" },
  { texto: "Realizar un reportaje fotográfico a tu pareja desnuda (máx 30 fotos eróticas).", tipo: "hot" },
  { texto: "Tu pareja desnuda te realizará sexo oral: ella dirá cuántos orgasmos y él dónde eyacular.", tipo: "hot" },
  { texto: "Tu pareja será tu esclavo/a sexual: realizará el acto tantas veces como te apetezca hoy.", tipo: "hot" },
  { texto: "Depilación morbosa: tu pareja dejará que le depiles sus partes íntimas, tú decides cuánto.", tipo: "hot" },
  { texto: "Atar a la pareja boca abajo con los ojos tapados durante máximo 60 minutos.", tipo: "hot" },
  { texto: "Realizar el sexo de manera grosera: usen vocabulario explícito y sucio sin cortarse.", tipo: "hot" },
  { texto: "Realizar sexo oral gourmet: pon comida o sirope en sus zonas íntimas y date un festín.", tipo: "hot" },
  { texto: "Frotaros y limpiaros mutuamente en la bañera o ducha, aprovechando la espuma.", tipo: "hot" },
  { texto: "Montaros el uno encima del otro (desnudos) y fingid que folláis con la ropa puesta.", tipo: "hot" },
  { texto: "Morréale mientras le magreas todo el cuerpo salvajemente.", tipo: "hot" },
  { texto: "Haz un striptease íntegro hasta quedar complemente desnud@.", tipo: "hot" },
  { texto: "Si eres hombre recorre su sexo con tu lengua. Si eres mujer hazle una buena mamadita.", tipo: "hot" },
  { texto: "Haz la mímica de una fellatio o un cunnilingus de forma exagerada.", tipo: "hot" },
  { texto: "Tu pareja te desviste y te deja en ropa interior para el resto del juego.", tipo: "hot" },
  { texto: "¡Al bidet! Tu pareja te lavará todas tus partes íntimas durante 3 minutos.", tipo: "hot" },
  { texto: "Lames y besas su espalda por 2 minutos, luego te quitas otra prenda.", tipo: "hot" },
  { texto: "Cómele los pezones y muérdelos suavemente durante 3 minutos.", tipo: "hot" },
  { texto: "Hacen un 69 solo durante 1 minuto, ¡sin llegar al orgasmo!", tipo: "hot" },
  { texto: "Véndale los ojos y átale las manos en cruz, tienes 3 minutos para hacerl@ gozar (sin orgasmo).", tipo: "hot" },
  { texto: "Masajea sus genitales con los tuyos, sin penetración, exítal@ durante 2 minutos.", tipo: "hot" },
  { texto: "Estimúl@ con un juguete sexual (real o improvisado) durante 1 minuto.", tipo: "hot" },
  { texto: "Derrama tu bebida favorita y bébela del cuerpo de tu pareja.", tipo: "hot" },
  { texto: "Penetras o te haces penetrar por tu pareja x 1 minuto estricto, sin orgasmo.", tipo: "hot" },
  { texto: "Eres su esclav@, tu am@ te somete a lo que se le antoje durante 5 minutos.", tipo: "hot" },
  { texto: "Estimúlale con tu boca y un cubito de hielo por 2 minutos.", tipo: "hot" },
  { texto: "Le das sexo oral durante 1 minuto y acompañas con la bebida que estén tomando.", tipo: "hot" },
  { texto: "Estimula a tu pareja analmente sin penetración, solo boca y manos por 2 min.", tipo: "hot" },
  { texto: "El muertito: tu pareja se tumba y no deberá reaccionar, hazle lo que quieras por 3 minutos.", tipo: "hot" },
  { texto: "Te ganaste un masaje genital con sus pies por 2 minutos.", tipo: "hot" },
  { texto: "Besa y lame el cuerpo desnudo de tu pareja acostada en una mesa.", tipo: "hot" }
];
